### ISSUE TITLE
Route incorrectly named

### ISSUE THREAD

**Issue by detside** [OpenClassrooms-Student-Center/5614116-go-fullstack-recipe-frontend#1]
In the exercise definition on openClassroom, the get request to retrieve a single recipe is named /api/recipe/:id. However, in the code, the route called is /api/recipes/:id. Not a huge deal but a bit of time is spent debugging.

**Comment by detside** [comment]
I am struggling to get my put and delete requests connected with the front end. The requests work as expected on postman but the delete does not work at all and the put give me a "form submission cancelled because form is not connected" warning. Can you help?

**Comment by willehpeh** [comment]
Hi!

Thanks for catching the typo in the activity! I have changed it to reflect the real route.

As for the put and delete routes, could you show me your code?  The "form submission cancelled" thing may be my fault in the front end app, I'll have a look.

**Comment by detside** [comment]
Hi Will,

My code is available here:
https://github.com/detside/OCR-Node-Express-Mongo-Tutorials/blob/master/exercise-1-backend/app.js

All the best,
Simon

**Comment by willehpeh** [comment]
Try changing your individual GET route from app.use to app.get.  It looks like your app hits the app.use route and goes no further (app.use applies to all verbs), so never gets as far as put or delete.

**Comment by detside** [comment]
Brilliant! Thanks for the help :)

I can finally submit my code! Would you suggest I remove my MongoDB creds
from the git repo before the submission?

**Comment by willehpeh** [comment]
You'll need to leave them there so that whomever is correcting you can test your app.  If you need to switch to a different database because you're using other parts of the one you're giving credentials for, don't hesitate to do so.  The advantage of using Atlas is that you can isolate DBs from each other.  Sound good?

**Comment by detside** [comment]
Perfect. That's what I thought but figured I'd ask as leaving credentials
on a public repo is not my favourite thing in the world :)

**Comment by willehpeh** [comment]
OK, no worries.  Marking issue as closed.
